name: Define Environment secrets for Azure Web App - fraud-detect
  
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: execute py script # email-from-python.py
        env:        
          KEY: ${{ secrets.KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
        run: python email-from-python.py